SHOW COLUMNS FROM CUSTOMERS;
SHOW COLUMNS FROM ORDERS; 
SHOW COLUMNS FROM PRODUCTS;

SHOW COLUMNS FROM DEPARTMENTS;
SHOW COLUMNS FROM EMPLOYEES;

SHOW COLUMNS FROM DOCTORS;
SHOW COLUMNS FROM PATIENTS;

-- Use an INNER JOIN to find customers who ordered products in a particular category, say category 1.
SELECT NAME ,PRODUCTNAME,CATEGORYID
FROM PRODUCTS JOIN ORDERS
ON ORDERS.PRODUCTID=PRODUCTS.PRODUCTID
JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID ;

-- Use a JOIN to show the products ordered by each customer, along with the total amount of each order.
SELECT PRODUCTNAME ,NAME,TOTALAMOUNT
FROM PRODUCTS JOIN ORDERS
ON ORDERS.PRODUCTID=PRODUCTS.PRODUCTID
JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID ;


-- Use an INNER JOIN to find employees and their performance scores for each department.
SELECT NAME,PERFORMANCESCORE ,DEPARTMENTNAME 
FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON DEPARTMENTS.DEPARTMENTID=EMPLOYEES.DEPARTMENTID;


-- Use a LEFT JOIN to list all employees and the departments they belong to, even if they don’t belong to any department.
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES
LEFT JOIN DEPARTMENTS 
ON DEPARTMENTS.DEPARTMENTID=EMPLOYEES.DEPARTMENTID;

-- Use an INNER JOIN to find all patients and their respective doctors' names.
SELECT NAME AS PATIENT_NAME,DOCTORNAME
FROM PATIENTS
JOIN DOCTORS
ON DOCTORS.DOCTORID=PATIENTS.DOCTORID;

-- Use multiple JOINs to show product names, their categories, and the customers who ordered them.
SELECT PRODUCTNAME ,CATEGORYID,NAME
FROM PRODUCTS JOIN ORDERS
ON ORDERS.PRODUCTID=PRODUCTS.PRODUCTID
JOIN CUSTOMERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID ;

-- Use a LEFT JOIN to find all customers and their orders, including those customers who haven't placed any orders.
SELECT NAME,ORDERID FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID ;

-- Use an INNER JOIN to find employees along with their department names.
SELECT NAME,DEPARTMENTNAME 
FROM EMPLOYEES
INNER  JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENTID=DEPARTMENTS.DEPARTMENTID;
