SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS; 
SELECT * FROM PRODUCTS;

SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;

SELECT * FROM DOCTORS;
SELECT * FROM PATIENTS;

-- Find employees and their department names using INNER JOIN.
SELECT NAME, DEPARTMENTNAME FROM EMPLOYEES
INNER JOIN DEPARTMENTS
ON EMPLOYEES.DEPARTMENTID=DEPARTMENTS.DEPARTMENTID;

-- Get a list of customers and their orders using LEFT JOIN.
SHOW COLUMNS FROM CUSTOMERS;
SHOW COLUMNS FROM ORDERS;
SHOW COLUMNS FROM PRODUCT;

SELECT NAME,ORDERID,PRODUCTNAME FROM CUSTOMERS
LEFT JOIN ORDERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID 
LEFT JOIN PRODUCTS
ON ORDERS.PRODUCTID=PRODUCTS.PRODUCTID;

-- Show the products ordered by customers along with product details using multiple joins.
SELECT PRODUCTS.*,ORDERID,NAME 
FROM PRODUCTS
LEFT JOIN ORDERS
ON PRODUCTS.PRODUCTID=ORDERS.PRODUCTID
LEFT JOIN  CUSTOMERS
ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID ;


-- Find doctors treating patients using INNER JOIN.
SHOW COLUMNS FROM DOCTORS;
SHOW COLUMNS FROM PATIENTS;

SELECT DOCTORNAME,NAME
FROM DOCTORS 
JOIN PATIENTS 
ON DOCTORS.DOCTORID=PATIENTS.DOCTORID;


-- Display departments with or without employees using RIGHT JOIN.
SHOW COLUMNS FROM DEPARTMENTS;
SHOW COLUMNS FROM EMPLOYEES;

SELECT *
FROM EMPLOYEES
RIGHT JOIN DEPARTMENTS 
ON DEPARTMENTS.DEPARTMENTID=EMPLOYEES.DEPARTMENTID;
